config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  # Define route for users in association with posts
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      post :auth, to: "authentication#create"
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/views/layouts/_comments_card.html.erb
<div class="px-1 -z-10">
  <h3 class="py-2 text-stone-600 text-xs font-bold">View <%= post.comments_count %> previous comments</h3>
  <% post.recent_comments.includes(:post, :author).each do |comment| %>
    <div class="flex items-center gap-3">
      <p class="text-xs pb-1 italic"><%= comment.author.name %>: <%= comment.text %></p>
      <% if can? :manage, comment %>
        <div class="cursor-pointer z-20">
        <%= link_to user_post_comment_path(comment.post.author, comment.post, comment), data: { turbo_method: :delete, turbo_confirm: 'Are you sure'} do |form| %>
        <button type="button">
        <i data-visualcompletion="css-img" style="background-image: url(&quot;https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/0uZ6-PjaiHq.png&quot;); background-position: 0px -1007px; background-size: auto; width: 20px; height: 20px; background-repeat: no-repeat; display: inline-block;"></i>
        </button>
      <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <ul>
    <% if msg.include?('own') %>
      <li class="text-red-500 text-sm mb-4"><%= msg %> ❌</li>
    <% else %>
      <li class="text-green-500 text-sm mb-4"><%= msg %> ✅</li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="relative bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900" data-controller="header">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="https://github.com/XsidX/blog_app" target="_blank" class="flex items-center">
      <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">BlogApp</span>
    </a>
    <div class="flex items-center md:order-2">
      <button data-header-target="openMyMenu" type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <% if current_user %>
          <img class="w-8 h-8 rounded-full" alt="user photo" src=<%= current_user.photo %>>
        <% else %>
          <img class="w-8 h-8 rounded-full" alt="user photo" src="https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y">
        <% end %>
      </button>
      <!-- Dropdown menu -->
      <div class="hidden absolute top-12 right-0 z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
           id="my-dropdown-menu"
           data-transition-enter="transition ease-out duration-100"
           data-transition-enter-start="transform opacity-0 scale-95"
           data-transition-enter-end="transform opacity-100 scale-100"
           data-transition-leave="transition ease-in duration-75"
           data-transition-leave-start="transform opacity-100 scale-100"
           data-transition-leave-end="transform opacity-0 scale-95"
      >
        <div class="py-3 px-4">
          <span class="block text-sm text-gray-900 dark:text-white"><%= current_user&.name %></span>
          <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%= current_user&.email %></span>
        </div>
        <ul class="py-1" aria-labelledby="user-menu-button">
          <li class="py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">
            <a href="#" class="block"><%= link_to 'My Profile',  edit_user_registration_path %></a>
          </li>
          <% if user_signed_in? %>
            <li class="py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">
              <a href="#" class="block" ><%= link_to 'Create a post', new_user_post_path(current_user) %></a>
            </li>
            <li class="py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">
              <a href="#" class="block"><%= link_to 'My posts', user_posts_path(current_user) %></a>
            </li>
          <% end %>
          <li>
            <a href="#" class="opacity-50 block py-2 px-4 text-sm text-gray-700 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">Settings</a>
          </li>
          <% unless user_signed_in? %>
            <li class="py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">
              <a href="#" class="block"><%= link_to 'Sign up', new_user_registration_path %></a>
            </li>
          <% end %>
          <li class="py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">
            <a href="#" class="block"><%= user_signed_in? ? link_to('Sign out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure'}) : link_to('Sign in', new_user_session_path) %></a>
          </li>
        </ul>
      </div>
    </div>
    <div class="justify-between items-center w-full md:flex md:w-auto md:order-1">
      <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li class="text-stone-700 hover:text-stone-400 transition ease-in duration-100">
          <a><%= link_to 'Home', root_path %></a>
        </li>
        <li data-header-target="openUserDropdown" class="text-stone-700 hover:text-stone-400 transition ease-in duration-100">
          <button
            class="flex justify-between items-center">
            Users
            <svg class="ml-1 w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </button>
          <!-- Dropdown menu -->
          <div
            class="hidden absolute top-12 z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
            id="user-dropdown-menu"
            data-transition-enter="transition ease-out duration-100"
            data-transition-enter-start="transform opacity-0 scale-95"
            data-transition-enter-end="transform opacity-100 scale-100"
            data-transition-leave="transition ease-in duration-75"
            data-transition-leave-start="transform opacity-100 scale-100"
            data-transition-leave-end="transform opacity-0 scale-95"
          >
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownNavbarButton">
              <li class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white transition ease-in duration-100">
                <a><%= link_to 'View authors', users_path %></a>
              </li>
              <li>
                <a class="opacity-50 block py-2 px-4 dark:hover:bg-gray-600 dark:hover:text-white transition ease-in duration-100">Become an author</a>
              </li>
            </ul>
          </div>
        </li>
        <li data-header-target="openPostDropdown" class="text-stone-700 hover:text-stone-400 transition ease-in duration-100">
          <button
            class="flex justify-between items-center">
            Posts
            <svg class="ml-1 w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </button>
          <!-- Dropdown menu -->
          <div
            class="hidden absolute top-12 z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
            id="post-dropdown-menu"
            data-transition-enter="transition ease-out duration-100"
            data-transition-enter-start="transform opacity-0 scale-95"
            data-transition-enter-end="transform opacity-100 scale-100"
            data-transition-leave="transition ease-in duration-75"
            data-transition-leave-start="transform opacity-100 scale-100"
            data-transition-leave-end="transform opacity-0 scale-95"
          >
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-400">
              <% @users&.each do |user| %>
              <li class="flex gap-2 items-center py-2 px-4 cursor-pointer group">
                  <button type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                    <%= link_to user_posts_path(user) do %>
                      <%= image_tag "#{user.photo.include?('https') ? user.photo : "https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y"}", class: "w-6 h-6 rounded-full" %>
                    <% end %>
                  </button>
                  <p class="text-stone-700 group-hover:text-stone-400"><%=link_to user.name, user_posts_path(user) %></p>
              </li>
              <% end %>
            </ul>
          </div>
        </li>
        <% if user_signed_in? %>
          <li class="text-stone-700 hover:text-stone-400 transition ease-in duration-100">
            <a><%= link_to 'Create a post', new_user_post_path(current_user) %></a>
          </li>
        <% end %>
        <li class="text-stone-700 group">
          <a class="flex items-center justify-center gap-1 group-hover:text-stone-400 transition ease-in duration-100" href="https://github.com/XsidX/blog_app" target="_blank" class="">
            Source
            <svg class="group-hover:fill-current" height="14" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="14" data-view-component="true">
              <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
            </svg>
          </a>
        </li>
      </ul>
    </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="relative bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900" data-controller="header">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="https://github.com/XsidX/blog_app" target="_blank" class="flex items-center">
      <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">BlogApp</span>
    </a>
    <div class="flex items-center md:order-2">
      <button data-header-target="openMyMenu" type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <img class="w-8 h-8 rounded-full" alt="user photo" src=<%= current_user&.photo %>>
      </button>
      <!-- Dropdown menu -->
      <div class="hidden absolute top-12 right-0 z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
           id="my-dropdown-menu"
           data-transition-enter="transition ease-out duration-100"
           data-transition-enter-start="transform opacity-0 scale-95"
           data-transition-enter-end="transform opacity-100 scale-100"
           data-transition-leave="transition ease-in duration-75"
           data-transition-leave-start="transform opacity-100 scale-100"
           data-transition-leave-end="transform opacity-0 scale-95"
      >
        <div class="py-3 px-4">
          <span class="block text-sm text-gray-900 dark:text-white"><%= current_user&.name %></span>
          <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%= current_user&.email %></span>
        </div>
        <ul class="py-1" aria-labelledby="user-menu-button">
          <li>
            <a href="#" class="opacity-50 block py-2 px-4 text-sm text-gray-700 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">Profile</a>
          </li>
          <li class="py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">
<!--            <a href="#" class="block" ><%#= link_to 'Create a post', new_user_post_path(current_user) %></a>-->
          </li>
          <li class="py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">
<!--            <a href="#" class="block"><%#= link_to 'My posts', user_posts_path(current_user) %></a>-->
          </li>
          <li>
            <a href="#" class="opacity-50 block py-2 px-4 text-sm text-gray-700 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100">Settings</a>
          </li>
          <li>
            <a href="#" class="block py-2 px-4 text-sm text-gray-700 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white transition ease-in duration-100"><%= user_signed_in? ? link_to('Sign out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure'}) : link_to('Sign in', new_user_session_path) %></a>
          </li>
        </ul>
      </div>
    </div>
    <div class="justify-between items-center w-full md:flex md:w-auto md:order-1">
      <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li class="text-stone-700 hover:text-stone-400 transition ease-in duration-100">
          <a><%= link_to 'Home', root_path %></a>
        </li>
        <li data-header-target="openUserDropdown" class="text-stone-700 hover:text-stone-400 transition ease-in duration-100">
          <button
            class="flex justify-between items-center">
            Users
            <svg class="ml-1 w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </button>
          <!-- Dropdown menu -->
          <div
            class="hidden absolute top-12 z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
            id="user-dropdown-menu"
            data-transition-enter="transition ease-out duration-100"
            data-transition-enter-start="transform opacity-0 scale-95"
            data-transition-enter-end="transform opacity-100 scale-100"
            data-transition-leave="transition ease-in duration-75"
            data-transition-leave-start="transform opacity-100 scale-100"
            data-transition-leave-end="transform opacity-0 scale-95"
          >
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownNavbarButton">
              <li class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white transition ease-in duration-100">
                <a><%= link_to 'View authors', users_path %></a>
              </li>
              <li>
                <a class="opacity-50 block py-2 px-4 dark:hover:bg-gray-600 dark:hover:text-white transition ease-in duration-100">Become an author</a>
              </li>
            </ul>
          </div>
        </li>
        <li data-header-target="openPostDropdown" class="text-stone-700 hover:text-stone-400 transition ease-in duration-100">
          <button
            class="flex justify-between items-center">
            Posts
            <svg class="ml-1 w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </button>
          <!-- Dropdown menu -->
          <div
            class="hidden absolute top-12 z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
            id="post-dropdown-menu"
            data-transition-enter="transition ease-out duration-100"
            data-transition-enter-start="transform opacity-0 scale-95"
            data-transition-enter-end="transform opacity-100 scale-100"
            data-transition-leave="transition ease-in duration-75"
            data-transition-leave-start="transform opacity-100 scale-100"
            data-transition-leave-end="transform opacity-0 scale-95"
          >
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-400">
              <% @users&.each do |user| %>
              <li class="flex gap-2 items-center py-2 px-4 cursor-pointer group">
                  <button type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                    <%= link_to user_posts_path(user) do %>
                      <%= image_tag "#{user.photo}", class: "w-6 h-6 rounded-full"%>
                    <% end %>
                  </button>
                  <p class="text-stone-700 group-hover:text-stone-400"><%=link_to user.name, user_posts_path(user) %></p>
              </li>
              <% end %>
            </ul>
          </div>
        </li>
        <li class="text-stone-700 hover:text-stone-400 transition ease-in duration-100">
<!--          <a><%#= link_to 'Create a post', new_user_post_path(current_user) %></a>-->
        </li>
        <li class="text-stone-700 group">
          <a class="flex items-center justify-center gap-1 group-hover:text-stone-400 transition ease-in duration-100" href="https://github.com/XsidX/blog_app" target="_blank" class="">
            Source
            <svg class="group-hover:fill-current" height="14" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="14" data-view-component="true">
              <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
            </svg>
          </a>
        </li>
      </ul>
    </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_post_card.html.erb
<div class="post-card relative bg-white drop-shadow-md p-4 mb-2" data-controller="modals">
  <h3 class="mb-2 text-sm font-bold"><%= post.title %> #<%= post.id %></h3>
  <% text_body = post.text.split(".").first(2).join(".") %>
  <h4 class="px-2 mb-2">
    <%= text_body %>...
    <button type="button" class="z-20 relative text-sm p-1 bg-white drop-shadow-sm hover:drop-shadow-lg text-stone-600 hover:text-gray-900 transition ease-in duration-100"><%= link_to 'Continue reading', user_post_path(@user, post) %></button>
  </h4>



  <div class="z-20 absolute top-0 right-0 text-xs bg-white rounded-md overflow-hidden drop-shadow-sm">
    <% if can? :manage, post %>
      <button type="button" class="p-2 hover:text-stone-500 transition ease-in duration-100"><%= link_to 'Edit', edit_user_post_path(@user, post) %></button>
      |
      <button type="button" class="p-2 hover:text-stone-600 transition ease-in duration-100"><%= link_to 'Delete', user_post_path(@user, post), data: { turbo_method: :delete, turbo_confirm: 'Are you sure'} %></button>
    <% end %>
  </div>
  <div class="flex gap-4 mt-4">
    <div class="z-20 relative mb-4">
      <div class="flex text-sm gap-3 pl-2">
        <%= form_with url: "/users/#{post.author_id}/posts/#{post.id}/likes" do |form| %>
          <button type="submit" class="flex items-center gap-1 text-blue-600 font-bold group">
            <%= image_tag "https://www.facebook.com/reaction/image/1635855486666999/?size=20&scale=1", class: "group-hover:scale-125 transition ease-in duration-100", style: "height: 18px; width: 18px;" %>
            <%= form.submit "#{post.likes_count}", class: "text-blue-600 font-bold" %>
          </button>
        <% end %>
        <button data-modals-target="openCommentInput" data-index="<%= post.id %>" type="button" class="comment-btn flex items-center gap-1 text-stone-600 font-semibold group">
          <i data-visualcompletion="css-img" class="group-hover:scale-110 transition ease-in duration-100" style="background-image: url(&quot;https://static.xx.fbcdn.net/rsrc.php/v3/yK/r/H6IBF1RX3vl.png&quot;); background-position: 0px -213px; background-size: auto; width: 18px; height: 18px; background-repeat: no-repeat; display: inline-block;"></i>
          Comment
        </button>
      </div>

      <!-- Comment dropdown input -->
      <div
        class="hidden z-30 mt-2 mb-4 bg-white text-sm rounded border border-gray-100 drop-shadow-md"
        id="comment-input-<%= post.id %>"
        data-transition-enter="transition ease-out duration-100"
        data-transition-enter-start="transform opacity-0 scale-95"
        data-transition-enter-end="transform opacity-100 scale-100"
        data-transition-leave="transition ease-in duration-75"
        data-transition-leave-start="transform opacity-100 scale-100"
        data-transition-leave-end="transform opacity-0 scale-95"
      >
        <div>
          <%= form_with model: comment, url: user_post_comments_path(post.author, post) do |form| %>
            <div class="relative w-96 h-32 focus:outline-none">
              <%= form.text_area :text, class: "w-full h-full border-none focus:ring-white text-sm text-stone-600 font-semibold italic", placeholder: "Add a comment..." %>
              <button
                type="submit"
                class="text-sm text-white bg-stone-500 hover:bg-stone-600 drop-shadow-lg py-1 px-2 cursor-pointer transition ease-in duration-100"
                id="comment-submit-<%= post.id %>"
              >
                Comment
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'layouts/comments_card', post: post %>
  <div data-modals-target="leaveCommentInput" data-index="<%= post.id %>" class="absolute inset-0 z-10"></div>
</div>

app/views/layouts/_user_card.html.erb
<div class="grid grid-cols-6 mb-4">
  <div class="col-span-1">
    <%= link_to user_path(user) do %>
      <img src=<%= user.photo %> class="object-cover" alt="<%= user.name %> profile">
    <% end %>
  </div>
  <div class="relative col-span-5 bg-stone-600 px-4 flex flex-col justify-center">
    <h2 class="text-white md:text-lg"><%= user.name %> #<%= user.id %></h2>
    <p class="absolute right-4 bottom-2 text-white text-xs md:text-sm font-bold">Number of posts: <%= user.posts_count %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <% if include_navbar? %>
    <%= render "layouts/navbar" %>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <main class="main p-4 md:px-48">
    <%= yield %>
  </main>
</body>
</html>